packages:
  - packages/*
  - packages/adapters/*
  - examples/*
  - apps/*
  - docs

onlyBuiltDependencies:
  - bufferutil
  - es5-ext
  - esbuild
  - tiny-secp256k1
  - utf-8-validate

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  node-forge@<1.3.2: '>=1.3.2'
  vite@>=5.2.6 <=5.4.20: '>=5.4.21'
  vite@>=7.1.0 <=7.1.10: '>=7.1.11'
