# Configurations
title:            XRPL Connect
longtitle:        A framework-agnostic wallet connection toolkit for the XRP Ledger
author:           XRPL Commons
email:            hello@xrpl-commons.org
description: >
  Complete documentation for XRPL Connect - a framework-agnostic wallet connection toolkit for the XRP Ledger.

version:          0.3.0
gitbook_version:  3.2.3

url:              'https://XRPL-Commons.github.io'
baseurl:          '/xrpl-connect'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink: /:name.html

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts
  - contrib
  - LICENSE
  - Makefile
  - README.md
  - docs-html-backup

collections:
  chapters:
    output: true
    permalink: /:collection/:name
    sort_by: weight

ordered_collections:
  - chapters

reveal:
  theme: "black"  # Options: beige, blood, league, moon, night, serif, simple, sky, solarized, white
  transition: "slide"  # Options: none, fade, slide, convex, concave, zoom

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  
scholar:
  style: _bibliography/my-apa-cv-no-access.csl
  locale: en

  sort_by: year
  order: descending

  source: _bibliography
  bibliography: gis
  bibliography_template: bibliography

  replace_strings: true

  query: "@*"

